// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar untuk Dokumentasi (Tutorial) - TETAP
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate dari folder docs/
    },
  ],
  
  // Sidebar BARU untuk Penggunaan
  penggunaanSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate dari folder penggunaan/
    },
  ],
};

module.exports = sidebars;
